import os
import json 
import logging
from pathlib import Path 
from typing import Optional

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# --- GENERAL SETTINGS ---
IMAGE_PATTERN = "*.jpg" 

# --- FLIR DATASET CONFIGURATION (Defaults) ---
FLIR_BASE_PATH_DEFAULT = "D:/Codes/499B/Datasets/FLIR Dataset" 
FLIR_JSON_MAP_FILENAME = "rgb_to_thermal_vid_map.json"
FLIR_VISIBLE_SUBDIR = os.path.join("video_rgb_test", "data")
FLIR_THERMAL_SUBDIR = os.path.join("video_thermal_test", "data")
FLIR_OUTPUT_SUBDIR_NAME = "video_fused_test_output_flir" 
FLIR_FUSED_FRAMES_SUBDIR_NAME = "data_fused"
FLIR_FUSED_VIDEO_FILENAME = "fused_flir_output.mp4" 
FLIR_SBS_VIDEO_FILENAME = "comparison_flir_sbs.mp4" 

# --- CAMEL DATASET CONFIGURATION (Defaults) ---
CAMEL_BASE_PATH_DEFAULT = "D:/Codes/499B/Datasets/CAMEL Datasets/Sequence 13"
CAMEL_SEQ_IR_TXT_FILENAME = "Seq13-IR.txt" 
CAMEL_SEQ_VIS_TXT_FILENAME = "Seq13-Vis.txt" 
CAMEL_INFO_TXT_FILENAME = "Seq13-info.txt"  
CAMEL_VISIBLE_SUBDIR = "vis" 
CAMEL_THERMAL_SUBDIR = "IR"   
CAMEL_IMAGE_FILENAME_FORMAT = "{:06d}.jpg" 
CAMEL_OUTPUT_SUBDIR_NAME = "video_fused_test_output_camel" 
CAMEL_FUSED_FRAMES_SUBDIR_NAME = "data_fused"
CAMEL_FUSED_VIDEO_FILENAME = "fused_camel_output.mp4"
CAMEL_SBS_VIDEO_FILENAME = "comparison_camel_sbs.mp4"

# --- DEFAULT ALGORITHM PARAMETERS ---
DEFAULT_CORE_FUSION_METHOD = "model2024"
# Parameters for "model2024"
DEFAULT_KERNEL_SIZE_M2024 = 15
DEFAULT_BASE_WEIGHT_M2024 = 0.5
DEFAULT_DETAIL_METHOD_M2024 = "max_abs"
# Parameters for "model2020"
DEFAULT_M2020_DECOMP_KSIZE = 11
DEFAULT_M2020_DECOMP_SIGMA = 5.0
DEFAULT_M2020_BASE_LAP_KSIZE = 3
DEFAULT_M2020_BASE_GAUSS_KSIZE = 11
DEFAULT_M2020_BASE_GAUSS_SIGMA = 5.0
DEFAULT_M2020_GUIDED_RADIUS = 7 
DEFAULT_M2020_GUIDED_EPS = 0.01  
DEFAULT_M2020_DETAIL_MEDIAN_KSIZE = 3
DEFAULT_M2020_DETAIL_LAP_KSIZE = 3
DEFAULT_M2020_DETAIL_WEIGHT_KSIZE = 11
DEFAULT_M2020_DETAIL_WEIGHT_SIGMA = 5.0
# Parameters for "model2015"
DEFAULT_M2015_GRAD_KSIZE = 3

# --- DEFAULT PROCESSING OPTIONS ---
DEFAULT_PROCESS_LIMIT = None
DEFAULT_NUM_WORKERS = None 
DEFAULT_VIDEO_FPS_OUTPUT = 30

# --- DEFAULT RESOLUTION FOR PIPELINE PROCESSING ---
DEFAULT_PIPELINE_TARGET_WIDTH = None # Or e.g., 1224
DEFAULT_PIPELINE_TARGET_HEIGHT = None # Or e.g., 1024

# --- ACTIVE PIPELINE SETTINGS (Placeholders) ---
ACTIVE_DATASET_NAME = "FLIR" 
BASE_PATH = Path(FLIR_BASE_PATH_DEFAULT)
VISIBLE_FRAMES_DIR = BASE_PATH / FLIR_VISIBLE_SUBDIR
THERMAL_FRAMES_DIR = BASE_PATH / FLIR_THERMAL_SUBDIR
JSON_MAP_FILE = BASE_PATH / FLIR_JSON_MAP_FILENAME
SEQ_VIS_TXT_FILE = None 
SEQ_IR_TXT_FILE = None  
INFO_TXT_FILE = None    
IMAGE_FILENAME_FORMAT = IMAGE_PATTERN

PIPELINE_TARGET_WIDTH = DEFAULT_PIPELINE_TARGET_WIDTH   
PIPELINE_TARGET_HEIGHT = DEFAULT_PIPELINE_TARGET_HEIGHT 

OUTPUT_FUSED_FRAMES_DIR = BASE_PATH / FLIR_OUTPUT_SUBDIR_NAME / FLIR_FUSED_FRAMES_SUBDIR_NAME
OUTPUT_FUSED_VIDEO_FILE = BASE_PATH / FLIR_OUTPUT_SUBDIR_NAME / FLIR_FUSED_VIDEO_FILENAME
OUTPUT_SIDE_BY_SIDE_VIDEO_FILE = BASE_PATH / FLIR_OUTPUT_SUBDIR_NAME / FLIR_SBS_VIDEO_FILENAME

# PIPELINE Specific Algorithm/Processing parameters
PIPELINE_CORE_FUSION_METHOD = DEFAULT_CORE_FUSION_METHOD
PIPELINE_KERNEL_SIZE_M2024 = DEFAULT_KERNEL_SIZE_M2024 
PIPELINE_BASE_WEIGHT_M2024 = DEFAULT_BASE_WEIGHT_M2024
PIPELINE_DETAIL_METHOD_M2024 = DEFAULT_DETAIL_METHOD_M2024

# Add model2020 pipeline defaults
PIPELINE_M2020_DECOMP_KSIZE = DEFAULT_M2020_DECOMP_KSIZE
PIPELINE_M2020_DECOMP_SIGMA = DEFAULT_M2020_DECOMP_SIGMA
PIPELINE_M2020_BASE_LAP_KSIZE = DEFAULT_M2020_BASE_LAP_KSIZE
PIPELINE_M2020_BASE_GAUSS_KSIZE = DEFAULT_M2020_BASE_GAUSS_KSIZE
PIPELINE_M2020_BASE_GAUSS_SIGMA = DEFAULT_M2020_BASE_GAUSS_SIGMA
PIPELINE_M2020_GUIDED_RADIUS = DEFAULT_M2020_GUIDED_RADIUS
PIPELINE_M2020_GUIDED_EPS = DEFAULT_M2020_GUIDED_EPS
PIPELINE_M2020_DETAIL_MEDIAN_KSIZE = DEFAULT_M2020_DETAIL_MEDIAN_KSIZE
PIPELINE_M2020_DETAIL_LAP_KSIZE = DEFAULT_M2020_DETAIL_LAP_KSIZE
PIPELINE_M2020_DETAIL_WEIGHT_KSIZE = DEFAULT_M2020_DETAIL_WEIGHT_KSIZE
PIPELINE_M2020_DETAIL_WEIGHT_SIGMA = DEFAULT_M2020_DETAIL_WEIGHT_SIGMA

# Add model2015 pipeline defaults
PIPELINE_M2015_GRAD_KSIZE = DEFAULT_M2015_GRAD_KSIZE

PIPELINE_TARGET_WIDTH = DEFAULT_PIPELINE_TARGET_WIDTH
PIPELINE_TARGET_HEIGHT = DEFAULT_PIPELINE_TARGET_HEIGHT
PIPELINE_PROCESS_LIMIT = DEFAULT_PROCESS_LIMIT
PIPELINE_NUM_WORKERS = DEFAULT_NUM_WORKERS
PIPELINE_VIDEO_FPS_OUTPUT = DEFAULT_VIDEO_FPS_OUTPUT

def set_active_dataset_config(dataset_type: str, base_path_override: Optional[str] = None):
    global ACTIVE_DATASET_NAME, BASE_PATH, VISIBLE_FRAMES_DIR, THERMAL_FRAMES_DIR
    global PIPELINE_TARGET_WIDTH, PIPELINE_TARGET_HEIGHT
    global JSON_MAP_FILE, SEQ_VIS_TXT_FILE, SEQ_IR_TXT_FILE, INFO_TXT_FILE, IMAGE_FILENAME_FORMAT
    global OUTPUT_FUSED_FRAMES_DIR, OUTPUT_FUSED_VIDEO_FILE, OUTPUT_SIDE_BY_SIDE_VIDEO_FILE
    global PIPELINE_CORE_FUSION_METHOD, PIPELINE_KERNEL_SIZE_M2024, PIPELINE_BASE_WEIGHT_M2024, PIPELINE_DETAIL_METHOD_M2024
    global PIPELINE_M2020_DECOMP_KSIZE, PIPELINE_M2020_DECOMP_SIGMA 
    global PIPELINE_M2020_BASE_LAP_KSIZE, PIPELINE_M2020_BASE_GAUSS_KSIZE, PIPELINE_M2020_BASE_GAUSS_SIGMA
    global PIPELINE_M2020_GUIDED_RADIUS, PIPELINE_M2020_GUIDED_EPS, PIPELINE_M2020_DETAIL_MEDIAN_KSIZE
    global PIPELINE_M2020_DETAIL_LAP_KSIZE, PIPELINE_M2020_DETAIL_WEIGHT_KSIZE, PIPELINE_M2020_DETAIL_WEIGHT_SIGMA
    global PIPELINE_M2015_GRAD_KSIZE
    global PIPELINE_PROCESS_LIMIT, PIPELINE_NUM_WORKERS, PIPELINE_VIDEO_FPS_OUTPUT, IMAGE_PATTERN

    logger.info(f"Setting active dataset configuration for: {dataset_type.upper()}")
    if dataset_type.lower() == "flir":
        ACTIVE_DATASET_NAME = "FLIR"; BASE_PATH = Path(base_path_override or FLIR_BASE_PATH_DEFAULT)
        VISIBLE_FRAMES_DIR = BASE_PATH / FLIR_VISIBLE_SUBDIR; THERMAL_FRAMES_DIR = BASE_PATH / FLIR_THERMAL_SUBDIR
        JSON_MAP_FILE = BASE_PATH / FLIR_JSON_MAP_FILENAME; SEQ_VIS_TXT_FILE = None; SEQ_IR_TXT_FILE = None
        INFO_TXT_FILE = None; IMAGE_FILENAME_FORMAT = None; IMAGE_PATTERN = "*.jpg"
        OUTPUT_FUSED_FRAMES_DIR = BASE_PATH / FLIR_OUTPUT_SUBDIR_NAME / FLIR_FUSED_FRAMES_SUBDIR_NAME
        OUTPUT_FUSED_VIDEO_FILE = BASE_PATH / FLIR_OUTPUT_SUBDIR_NAME / FLIR_FUSED_VIDEO_FILENAME
        OUTPUT_SIDE_BY_SIDE_VIDEO_FILE = BASE_PATH / FLIR_OUTPUT_SUBDIR_NAME / FLIR_SBS_VIDEO_FILENAME

    elif dataset_type.lower() == "camel":
        ACTIVE_DATASET_NAME = "CAMEL"; BASE_PATH = Path(base_path_override or CAMEL_BASE_PATH_DEFAULT)
        VISIBLE_FRAMES_DIR = BASE_PATH / CAMEL_VISIBLE_SUBDIR; THERMAL_FRAMES_DIR = BASE_PATH / CAMEL_THERMAL_SUBDIR
        JSON_MAP_FILE = None; SEQ_VIS_TXT_FILE = BASE_PATH / CAMEL_SEQ_VIS_TXT_FILENAME
        SEQ_IR_TXT_FILE = BASE_PATH / CAMEL_SEQ_IR_TXT_FILENAME; INFO_TXT_FILE = BASE_PATH / CAMEL_INFO_TXT_FILENAME
        IMAGE_FILENAME_FORMAT = CAMEL_IMAGE_FILENAME_FORMAT
        IMAGE_PATTERN = CAMEL_IMAGE_FILENAME_FORMAT.format(0).replace('0','*') if CAMEL_IMAGE_FILENAME_FORMAT else "*.jpg"
        OUTPUT_FUSED_FRAMES_DIR = BASE_PATH / CAMEL_OUTPUT_SUBDIR_NAME / CAMEL_FUSED_FRAMES_SUBDIR_NAME
        OUTPUT_FUSED_VIDEO_FILE = BASE_PATH / CAMEL_OUTPUT_SUBDIR_NAME / CAMEL_FUSED_VIDEO_FILENAME
        OUTPUT_SIDE_BY_SIDE_VIDEO_FILE = BASE_PATH / CAMEL_OUTPUT_SUBDIR_NAME / CAMEL_SBS_VIDEO_FILENAME

    else:
        logger.error(f"Unsupported dataset_type: {dataset_type}. Using FLIR defaults.")
        set_active_dataset_config("flir", base_path_override); return

    PIPELINE_CORE_FUSION_METHOD = DEFAULT_CORE_FUSION_METHOD 
    PIPELINE_KERNEL_SIZE_M2024 = DEFAULT_KERNEL_SIZE_M2024 
    PIPELINE_BASE_WEIGHT_M2024 = DEFAULT_BASE_WEIGHT_M2024 
    PIPELINE_DETAIL_METHOD_M2024 = DEFAULT_DETAIL_METHOD_M2024 
    
    PIPELINE_M2020_DECOMP_KSIZE = DEFAULT_M2020_DECOMP_KSIZE
    PIPELINE_M2020_DECOMP_SIGMA = DEFAULT_M2020_DECOMP_SIGMA
    PIPELINE_M2020_BASE_LAP_KSIZE = DEFAULT_M2020_BASE_LAP_KSIZE
    PIPELINE_M2020_BASE_GAUSS_KSIZE = DEFAULT_M2020_BASE_GAUSS_KSIZE
    PIPELINE_M2020_BASE_GAUSS_SIGMA = DEFAULT_M2020_BASE_GAUSS_SIGMA
    PIPELINE_M2020_GUIDED_RADIUS = DEFAULT_M2020_GUIDED_RADIUS
    PIPELINE_M2020_GUIDED_EPS = DEFAULT_M2020_GUIDED_EPS
    PIPELINE_M2020_DETAIL_MEDIAN_KSIZE = DEFAULT_M2020_DETAIL_MEDIAN_KSIZE
    PIPELINE_M2020_DETAIL_LAP_KSIZE = DEFAULT_M2020_DETAIL_LAP_KSIZE
    PIPELINE_M2020_DETAIL_WEIGHT_KSIZE = DEFAULT_M2020_DETAIL_WEIGHT_KSIZE
    PIPELINE_M2020_DETAIL_WEIGHT_SIGMA = DEFAULT_M2020_DETAIL_WEIGHT_SIGMA
    
    PIPELINE_M2015_GRAD_KSIZE = DEFAULT_M2015_GRAD_KSIZE
    
    PIPELINE_PROCESS_LIMIT = DEFAULT_PROCESS_LIMIT
    PIPELINE_NUM_WORKERS = DEFAULT_NUM_WORKERS
    PIPELINE_VIDEO_FPS_OUTPUT = DEFAULT_VIDEO_FPS_OUTPUT
    PIPELINE_TARGET_WIDTH = DEFAULT_PIPELINE_TARGET_WIDTH
    PIPELINE_TARGET_HEIGHT = DEFAULT_PIPELINE_TARGET_HEIGHT
    
    logger.info(f" ACTIVE CONFIG - Dataset: {ACTIVE_DATASET_NAME}, Core Fusion: {PIPELINE_CORE_FUSION_METHOD}")
    logger.info(f" ACTIVE CONFIG - Base Path: {BASE_PATH}")
    logger.info(f" ACTIVE CONFIG - Output Fused Frames: {OUTPUT_FUSED_FRAMES_DIR}")
    logger.info(f" ACTIVE CONFIG - Target Pipeline Res: {PIPELINE_TARGET_WIDTH}x{PIPELINE_TARGET_HEIGHT if PIPELINE_TARGET_WIDTH else 'Native'}")